### ISSUE TITLE
[FEATURE] Name new playlist popup

### ISSUE THREAD

**Issue by rowanh22** [Sapphire-Snail/Democrify#22]
**User Story**
For example: 
As a developer I want to add a popup which lets the user name the playlist they're creating.

**Priority**
- [ ] High
- [ ] Medium
- [x] Low

**Describe the solution you want to implement**
Simple react popup with input box and create/cancel buttons, that passes the entered text through to current endpoint.

**Comment by dder725** [comment]
Closed as a duplicate of #36 =) I should have had a better look at the existing issues
