### ISSUE TITLE
[FEATURE] Favicon and app's title on browser tab

### ISSUE THREAD

**Issue by dder725** [Sapphire-Snail/Democrify#27]
**User Story**
As a user,
I want to see favicon and the name of the app,
So I can navigate to it easily if I have multiple tabs open

**Priority**
- [ ] High
- [ ] Medium
- [x] Low

**Describe the solution you want to implement**
Change the favicon and the app's title

**Describe alternatives you've considered**
n/a
**Issue Dependencies**
n/a
**Additional context**
A favicon needs to be made to reflect either the app's name or functionality. Possibly a lowercase d, or a music note. Up to assignee's discretion :) The current look is shown below (not good)

![image](https://user-images.githubusercontent.com/42598015/80359039-61e28900-88d1-11ea-9275-7daaac165a19.png)

**Comment by chrisglutton** [comment]
I don't think spotify offer the function to like this song;(

**Comment by dder725** [comment]
Closed via one of the final design PRs
