### ISSUE TITLE
[FEATURE] Create playlist popup

### ISSUE THREAD

**Issue by dder725** [Sapphire-Snail/Democrify#36]
**User Story**
As a user,
I want to be able to create a new playlist,
So I can use it for the app

**Priority**
- [x] High
- [ ] Medium
- [ ] Low

**Describe the solution you want to implement**
Upon clicking on the 'New playlist' button a pop up modal appears where a user can specify the playlist's name. Once the user presses OK, the playlist is added to their account.

**Issue Dependencies**
n/a

**Additional context**

**Comment by chrisglutton** [comment]
think i done it, but dont know how to get it online
