### ISSUE TITLE
[FEATURE] Previous song playlist button

### ISSUE THREAD

**Issue by dder725** [Sapphire-Snail/Democrify#47]
**User Story**
As a user,
I want to be able to go back a song,
So I can re-listen to it

**Priority**
- [ ] High
- [x] Medium
- [ ] Low

**Describe the solution you want to implement**
The player has a '<|' button that lets the user go back to the previous song. If the current song the first one on the list, the button is inactive.

**Issue Dependencies**
n/a

**Comment by chrisglutton** [comment]
go back to the previous song is done. I added a seek function, so if click it when playing the fisrt song, it goes back to the head of the song.
